ALTER ROLE [db_owner] ADD MEMBER [DESKTOP-9JH6FOM\georg];


GO
ALTER ROLE [db_owner] ADD MEMBER [DESKTOP-9JH6FOM\paulb];


GO
ALTER ROLE [db_owner] ADD MEMBER [DESKTOP-9JH6FOM\johnb];


GO
ALTER ROLE [db_owner] ADD MEMBER [DESKTOP-9JH6FOM\ringo];


GO
ALTER ROLE [db_securityadmin] ADD MEMBER [DESKTOP-9JH6FOM\mmber];

