create procedure [sp_MSins_SalesSalesOrderHeader]
    @c1 int,
    @c2 tinyint,
    @c3 datetime,
    @c4 datetime,
    @c5 datetime,
    @c6 tinyint,
    @c7 bit,
    @c8 nvarchar(25),
    @c9 nvarchar(15),
    @c10 int,
    @c11 int,
    @c12 int,
    @c13 int,
    @c14 int,
    @c15 int,
    @c16 int,
    @c17 varchar(15),
    @c18 int,
    @c19 money,
    @c20 money,
    @c21 money,
    @c22 nvarchar(128),
    @c23 uniqueidentifier,
    @c24 datetime
as
begin  
	insert into [Sales].[SalesOrderHeader] (
		[SalesOrderID],
		[RevisionNumber],
		[OrderDate],
		[DueDate],
		[ShipDate],
		[Status],
		[OnlineOrderFlag],
		[PurchaseOrderNumber],
		[AccountNumber],
		[CustomerID],
		[SalesPersonID],
		[TerritoryID],
		[BillToAddressID],
		[ShipToAddressID],
		[ShipMethodID],
		[CreditCardID],
		[CreditCardApprovalCode],
		[CurrencyRateID],
		[SubTotal],
		[TaxAmt],
		[Freight],
		[Comment],
		[rowguid],
		[ModifiedDate]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24	) 
end  
