create procedure [sp_MSins_ProductionProduct]
    @c1 int,
    @c2 nvarchar(50),
    @c3 nvarchar(25),
    @c4 bit,
    @c5 bit,
    @c6 nvarchar(15),
    @c7 smallint,
    @c8 smallint,
    @c9 money,
    @c10 money,
    @c11 nvarchar(5),
    @c12 nchar(3),
    @c13 nchar(3),
    @c14 decimal(8,2),
    @c15 int,
    @c16 nchar(2),
    @c17 nchar(2),
    @c18 nchar(2),
    @c19 int,
    @c20 int,
    @c21 datetime,
    @c22 datetime,
    @c23 datetime,
    @c24 uniqueidentifier,
    @c25 datetime
as
begin  
	insert into [Production].[Product] (
		[ProductID],
		[Name],
		[ProductNumber],
		[MakeFlag],
		[FinishedGoodsFlag],
		[Color],
		[SafetyStockLevel],
		[ReorderPoint],
		[StandardCost],
		[ListPrice],
		[Size],
		[SizeUnitMeasureCode],
		[WeightUnitMeasureCode],
		[Weight],
		[DaysToManufacture],
		[ProductLine],
		[Class],
		[Style],
		[ProductSubcategoryID],
		[ProductModelID],
		[SellStartDate],
		[SellEndDate],
		[DiscontinuedDate],
		[rowguid],
		[ModifiedDate]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25	) 
end  
