CREATE TABLE [dbo].[ViewMetadata] (
    [VIEW_NAME]          VARCHAR (250) NULL,
    [COLUMN_NAME]        VARCHAR (250) NULL,
    [COLUMN_DESCRIPTION] VARCHAR (250) NULL,
    [SOURCE_SYSTEM]      VARCHAR (250) NULL,
    [SOURCE_TABLE]       VARCHAR (250) NULL,
    [SOURCE_COLUMN]      VARCHAR (250) NULL,
    [COLUMN_ISLOGIC]     VARCHAR (1)   NULL,
    [COLUMN_LEGACY]      VARCHAR (250) NULL
);

