--drop view [Model].[DimCustomerView]

CREATE VIEW [Model].[DimCustomerView]
AS
SELECT [CustomerKey] AS 'Customer Key'
      ,[StartDate] AS 'Customer Row Creation Date'
      ,[EndDate] AS 'Customer Row Closed Date'
	  ,CASE WHEN [EndDate] IS NULL THEN 1 ELSE 0 END  AS 'Customer Current Row Flag'
      ,[CustomerID]						   AS 'Customer ID'
      ,[CustomerTitle]					   AS 'Customer Title'
      ,[CustomerFirstName]				   AS 'Customer First Name'
      ,[CustomerMiddleName]				   AS 'Customer Middle Name'
      ,[CustomerLastName]				   AS 'Customer LastName'
      ,[CustomerDOB]					   AS 'Customer DOB'
      ,[CustomerMaritalStatus]			   AS 'Customer Marital Status'
      ,[CustomerGender]					   AS 'Customer Gender'
      ,[CustomerAddressLine1]			   AS 'Customer Address Line 1'
      ,[CustomerAddressLine2]			   AS 'Customer Address Line 2'
      ,[CustomerCity]					   AS 'Customer City'
      ,[CustomerStateProvinceCode]		   AS 'Customer State Province Code'
      ,[CustomerStateProvinceName]		   AS 'Customer State Province Name'
      ,[CustomerCountryRegionCode]		   AS 'Customer Country Region Code'
      ,[CustomerCountryRegionName]		   AS 'Customer Country Region Name'
      ,[CustomerSalesTerritoryName]		   AS 'Customer Sales Territory Name'
      ,[CustomerSalesTerritoryGroup]	   AS 'Customer Sales Territory Group'
      ,[CustomerPostCode]				   AS 'Customer Post Code'
      ,[CustomerPhone]					   AS 'Customer Phone'
      ,[CustomerEmailAddress]			   AS 'Customer Email Address'
      ,[CustomerAnualIncome]			   AS 'Customer Anual Income'
      ,[CustomerTotalChildren]			   AS 'Customer Total Children'
      ,[CustomerChildrenAtHome]			   AS 'Customer Children At Home'
      ,[CustomerEducation]				   AS 'Customer Education'
      ,[CustomerOccupation]				   AS 'Customer Occupation'
      ,[CustomerIsHomeOwner]			   AS 'Customer Is Home Owner'
      ,[CustomerNumberOfVehicles]		   AS 'Customer Number Of Vehicles'
      ,[CustomerFirstPurchaseDate]		   AS 'Customer First Purchase Date'
      ,[CustomerCommuteDistance]		   AS 'Customer Commute Distance'
  FROM [Model].[DimCustomer];
