
CREATE VIEW [Model].[DimDateView]
AS
SELECT [DateKey] AS 'Date Key'
	,ISNULL([FullDate],'01-jan-1900') AS 'Date'
	,[FullDate] AS 'Full Date'
	,[DateName] AS 'Date Name'
	,[DayOfWeek] AS 'Day Of Week'
	,[DayNameOfWeek] AS 'Day Name Of Week'
	,[DayOfMonth] AS 'Day Of Month'
	,[WorkingDayOfMonth] AS 'Working Day Of Month'
	,[IsUKBankHoliday] AS 'Is UK Bank Holiday'
	,[UKBankHoliday] AS 'UK Bank Holiday Name'
	,[DayOfYear] AS 'Day Of Year'
	,[WeekdayWeekend] AS 'Weekday Or Weekend'
	,[WeekOfYear] AS 'Week No. Of Year'
	,[MonthName] AS 'Month Name'
	,[MonthOfYear] AS 'Month No. Of Year'
	,[IsLastDayOfMonth] 'Is Last Day Of Month'
	,[CalendarQuarter] AS 'Calendar Quarter'
	,[CalendarYear] AS 'Calendar Year'
	,[CalendarYearMonth] AS 'Calendar Year Month'
	,[CalendarYearQtr] AS 'Calendar Year And Qtr'
	,[FiscalMonthOfYear] AS 'Fiscal Month Of Year'
	,[FiscalQuarter] AS 'Fiscal Quarter'
	,[FiscalYear] AS 'Fiscal Year'
	,[FiscalYearMonth] AS 'Fiscal Year and Month'
	,[FiscalYearQtr] AS 'Fiscal Year and Quarter'
    ,[FourCQuarter]	AS 'FourC Quarter'
    ,[FourCYear]	AS 'FourC Year'
    ,[FourCYearQtr] AS 'FourC Year and Quarter'
FROM [Model].[DimDate] WITH (NOLOCK);
