CREATE VIEW [Model].[DimEmployeeView]
AS
SELECT [EmployeeKey] AS 'Employee Key'
      ,[StartDate] AS 'Employee Row Creation Date'
      ,[EndDate] AS 'Employee Row Closed Date'
	  ,CASE WHEN [EndDate] IS NULL THEN 1 ELSE 0 END  AS 'Employee Current Row Flag'
      ,[EmployeeCode] AS 'Employee Code'
      ,[EmployeeDepartment] AS 'Employee Department'
      ,[EmployeeDepartmentGroupName] AS 'Employee Department Group Name'
      ,[EmployeeDepartmentStartDate] AS 'Employee Department Start Date'
      ,[EmployeeTitle] AS 'Employee Title'
      ,[EmployeeFirstName] AS 'Employee First Name'
      ,[EmployeeMiddleName] AS 'Employee Middle Name'
      ,[EmployeeLastName] AS 'Employee Last Name'
      ,[EmployeeSuffix] AS 'Employee Suffix'
      ,[EmployeeJobTitle] AS 'Employee Job Title'
      ,[EmployeePhoneNumber] AS 'Employee Phone Number'
      ,[EmployeePhoneNumberType] AS 'Employee Phone Number Type'
      ,[EmployeeEmailAddress] AS 'Employee Email Address'
      ,[EmployeeEmailPromotion] AS 'Employee Email Promotion'
      ,[EmployeeAddressLine1] AS 'Employee Address Line 1'
      ,[EmployeeAddressLine2]  AS 'Employee Address Line 2'
      ,[EmployeeCity] AS 'Employee City'
      ,[EmployeeStateProvinceName] AS 'Employee State Province Name'
      ,[EmployeePostalCode] AS 'Employee Postal Code'
      ,[EmployeeCountryRegionName] AS 'Employee Country Region Name'
  FROM [Model].[DimEmployee];
