CREATE VIEW [Model].[DimProductView]
AS
SELECT [ProductKey]						AS 'Product Key'
	  ,[StartDate]						AS 'Product Row Creation Date'
	  ,[EndDate]						AS 'Product Row Closed Date'
	  ,CASE  WHEN [EndDate] IS NULL  THEN 1 ELSE 0 END AS 'Product Current Row Flag'
      ,[ProductCode]					AS 'Product Code'
      ,[ProductCategoryName]			AS 'Product Category Name'
      ,[ProductSubcategoryName]			AS 'Product Subcategory Name'
      ,[ProductWeightUnitMeasureCode]	AS 'Product Weight Unit Measure Code'
      ,[ProductSizeUnitMeasureCode]		AS 'Product Size Unit Measure Code'
      ,[ProductName]					AS 'Product Name'
      ,[ProductStandardCost]			AS 'Product Standard Cost'
      ,[ProductFinishedGoodsFlag]		AS 'Product Finished Goods Flag'
      ,[ProductColour]					AS 'Product Colour'
      ,[ProductSafetyStockLevel]		AS 'Product Safety Stock Level'
      ,[ProductReorderPoint]			AS 'Product Reorder Point'
      ,[ProductListPrice]				AS 'Product List Price'
      ,[ProductSize]					AS 'Product Size'
      ,[ProductSizeRange]				AS 'Product Size Range'
      ,[ProductWeight]					AS 'Product Weight'
      ,[ProductDaysToManufacture]		AS 'Product Days To Manufacture'
      ,[ProductLine]					AS 'Product Line'
      ,[DealerPrice]					AS 'Dealer Price'
      ,[ProductClass]					AS 'Product Class'
      ,[ProductStyle]					AS 'Product Style'
      ,[ProductModelName]				AS 'Product Model Name'
      ,[ProductLargePhoto]				AS 'Product Large Photo'
      ,[ProductDescription]				AS 'Product Description'
      ,[ProductID]						AS 'Product ID'
  FROM [Model].[DimProduct]