CREATE VIEW [Model].[FactResellerSalesView]
AS
SELECT [ProductKey]										AS 'Product Key'
      ,[OrderDateKey]									AS 'Order Date Key'
      ,[DueDateKey]										AS 'Due Date Key'
      ,[ShipDateKey]									AS 'Ship Date Key'
      ,[ResellerKey]									AS 'Reseller Key'
      ,[EmployeeKey]									AS 'Employee Key'
      ,[PromotionKey]									AS 'Promotion Key'
      ,[CurrencyKey]									AS 'Currency Key'
      ,[SalesTerritoryKey]								AS 'Sales Territory Key'
      ,[ResellerSalesOrderNumber]						AS 'Reseller Sales Order Number'
      ,[ResellerSalesOrderLineNumber]					AS 'Reseller Sales Order Line Number'
      ,[ResellerSalesRevisionNumber]					AS 'Reseller Sales Revision Number'
      ,[ResellerSalesOrderQuantity]						AS 'Reseller Sales Order Quantity'
      ,[ResellerSalesUnitPrice]							AS 'Reseller Sales Unit Price'
      ,[ResellerSalesExtendedAmount]					AS 'Reseller Sales Extended Amount'
      ,[ResellerSalesUnitPriceDiscountPercentage]		AS 'Reseller Sales Unit Price Discount Percentage'
      ,[ResellerSalesDiscountAmount]					AS 'Reseller Sales Discount Amount'
      ,[ResellerSalesUnitProductStandardCost]			AS 'Reseller Sales Unit Product Standard Cost'
      ,[ResellerSalesTotalProductCost]					AS 'Reseller Sales Total Product Cost'
      ,[ResellerSalesAmount]							AS 'Reseller Sales Amount'
      ,[ResellerSalesTaxAmount]							AS 'Reseller Sales Tax Amount'
      ,[ResellerSalesFreightAmount]						AS 'Reseller Sales Freight Amount'
      ,[CarrierTrackingNumber]							AS 'Reseller Sales Carrier Tracking Number'
      ,[PurchaseOrderNumber]							AS 'Reseller Sales Purchase Order Number'
      ,[OrderDate]										AS 'Reseller Sales Order Date'
      ,[DueDate]										AS 'Reseller Sales Due Date'
      ,[ShipDate]										AS 'Reseller Sales Ship Date'
  FROM [Model].[FactResellerSales];

