CREATE TABLE [Transform].[DimCustomerChangesViewPersisted] (
    [CustomerID]                  VARCHAR (10)  NULL,
    [CustomerTitle]               NVARCHAR (8)  NULL,
    [CustomerFirstName]           NVARCHAR (50) NULL,
    [CustomerMiddleName]          NVARCHAR (50) NULL,
    [CustomerLastName]            NVARCHAR (50) NULL,
    [CustomerDOB]                 DATE          NULL,
    [CustomerMaritalStatus]       VARCHAR (1)   NULL,
    [CustomerGender]              VARCHAR (1)   NULL,
    [CustomerAddressLine1]        NVARCHAR (60) NULL,
    [CustomerAddressLine2]        NVARCHAR (60) NULL,
    [CustomerCity]                NVARCHAR (30) NULL,
    [CustomerStateProvinceCode]   NCHAR (3)     NULL,
    [CustomerStateProvinceName]   NVARCHAR (50) NULL,
    [CustomerCountryRegionCode]   NVARCHAR (3)  NULL,
    [CustomerCountryRegionName]   NVARCHAR (50) NULL,
    [CustomerSalesTerritoryName]  NVARCHAR (50) NULL,
    [CustomerSalesTerritoryGroup] NVARCHAR (50) NULL,
    [CustomerPostCode]            NVARCHAR (15) NULL,
    [CustomerPhone]               NVARCHAR (25) NULL,
    [CustomerEmailAddress]        NVARCHAR (50) NULL,
    [CustomerAnualIncome]         VARCHAR (64)  NULL,
    [CustomerTotalChildren]       INT           NULL,
    [CustomerChildrenAtHome]      INT           NULL,
    [CustomerEducation]           VARCHAR (64)  NULL,
    [CustomerOccupation]          VARCHAR (64)  NULL,
    [CustomerIsHomeOwner]         BIT           NULL,
    [CustomerNumberOfVehicles]    INT           NULL,
    [CustomerFirstPurchaseDate]   DATE          NULL,
    [CustomerCommuteDistance]     VARCHAR (64)  NULL
);

