CREATE TABLE [Transform].[DimEmployeeChanges] (
    [EmployeeKey]                 INT          NOT NULL,
    [ExecutionID]                 BIGINT       NOT NULL,
    [SCDBitmap]                   INT          NOT NULL,
    [StartDate]                   DATETIME     NOT NULL,
    [EndDate]                     DATETIME     NULL,
    [IsLateArrivingMember]        BIT          NOT NULL,
    [EmployeeCode]                INT          NOT NULL,
    [EmployeeDepartment]          VARCHAR (50) DEFAULT ('') NOT NULL,
    [EmployeeDepartmentGroupName] VARCHAR (50) DEFAULT ('') NOT NULL,
    [EmployeeDepartmentStartDate] DATE         DEFAULT ('01 JAN 1900') NOT NULL,
    [EmployeeTitle]               VARCHAR (8)  NULL,
    [EmployeeFirstName]           VARCHAR (50) DEFAULT ('') NOT NULL,
    [EmployeeMiddleName]          VARCHAR (50) NULL,
    [EmployeeLastName]            VARCHAR (50) DEFAULT ('') NOT NULL,
    [EmployeeSuffix]              VARCHAR (10) NULL,
    [EmployeeJobTitle]            VARCHAR (50) DEFAULT ('') NOT NULL,
    [EmployeePhoneNumber]         VARCHAR (25) NULL,
    [EmployeePhoneNumberType]     VARCHAR (50) DEFAULT ('') NULL,
    [EmployeeEmailAddress]        VARCHAR (50) DEFAULT ('') NOT NULL,
    [EmployeeEmailPromotion]      INT          DEFAULT ((0)) NOT NULL,
    [EmployeeAddressLine1]        VARCHAR (50) NULL,
    [EmployeeAddressLine2]        VARCHAR (50) NULL,
    [EmployeeCity]                VARCHAR (50) DEFAULT ('') NOT NULL,
    [EmployeeStateProvinceName]   VARCHAR (50) DEFAULT ('') NOT NULL,
    [EmployeePostalCode]          VARCHAR (50) DEFAULT ('') NOT NULL,
    [EmployeeCountryRegionName]   VARCHAR (50) DEFAULT ('') NOT NULL
);

