CREATE TABLE [Transform].[DimProductChanges] (
    [ProductKey]                   INT             NULL,
    [ExecutionID]                  BIGINT          NOT NULL,
    [SCDBitmap]                    INT             NOT NULL,
    [StartDate]                    DATETIME        NOT NULL,
    [EndDate]                      DATETIME        NULL,
    [IsLateArrivingMember]         BIT             NOT NULL,
    [ProductCode]                  NVARCHAR (25)   NOT NULL,
    [ProductCategoryName]          NVARCHAR (50)   NULL,
    [ProductSubcategoryName]       NVARCHAR (50)   NULL,
    [ProductWeightUnitMeasureCode] NCHAR (3)       NULL,
    [ProductSizeUnitMeasureCode]   NCHAR (3)       NULL,
    [ProductName]                  NVARCHAR (50)   DEFAULT ('') NOT NULL,
    [ProductStandardCost]          MONEY           DEFAULT ((0.00)) NOT NULL,
    [ProductFinishedGoodsFlag]     BIT             DEFAULT ((0)) NOT NULL,
    [ProductColour]                NVARCHAR (15)   DEFAULT ('') NOT NULL,
    [ProductSafetyStockLevel]      SMALLINT        DEFAULT ((0)) NOT NULL,
    [ProductReorderPoint]          SMALLINT        DEFAULT ((0)) NOT NULL,
    [ProductListPrice]             MONEY           DEFAULT ((0.00)) NOT NULL,
    [ProductSize]                  NVARCHAR (5)    NULL,
    [ProductSizeRange]             NVARCHAR (8)    DEFAULT ('') NOT NULL,
    [ProductWeight]                DECIMAL (8, 2)  NULL,
    [ProductDaysToManufacture]     INT             DEFAULT ((0)) NOT NULL,
    [ProductLine]                  NCHAR (2)       NULL,
    [DealerPrice]                  MONEY           NULL,
    [ProductClass]                 NCHAR (2)       NULL,
    [ProductStyle]                 NCHAR (2)       NULL,
    [ProductModelName]             NVARCHAR (50)   NULL,
    [ProductLargePhoto]            VARBINARY (MAX) NULL,
    [ProductDescription]           NVARCHAR (400)  NULL,
    [ProductID]                    INT             DEFAULT ((0)) NOT NULL
);

