CREATE TABLE [Transform].[FactResellerSalesChanges] (
    [ExecutionID]                              BIGINT          NOT NULL,
    [PartitionKey]                             DATE            NOT NULL,
    [ProductKey]                               INT             NOT NULL,
    [OrderDateKey]                             INT             NOT NULL,
    [DueDateKey]                               INT             NOT NULL,
    [ShipDateKey]                              INT             NOT NULL,
    [ResellerKey]                              INT             NOT NULL,
    [EmployeeKey]                              INT             NOT NULL,
    [PromotionKey]                             INT             NOT NULL,
    [CurrencyKey]                              INT             NOT NULL,
    [SalesTerritoryKey]                        INT             NOT NULL,
    [ResellerSalesOrderNumber]                 INT             NOT NULL,
    [ResellerSalesOrderLineNumber]             INT             NULL,
    [ResellerSalesRevisionNumber]              INT             NOT NULL,
    [ResellerSalesOrderQuantity]               INT             NOT NULL,
    [ResellerSalesUnitPrice]                   DECIMAL (18, 4) NOT NULL,
    [ResellerSalesExtendedAmount]              DECIMAL (18, 4) NULL,
    [ResellerSalesUnitPriceDiscountPercentage] DECIMAL (18, 4) NOT NULL,
    [ResellerSalesDiscountAmount]              DECIMAL (18, 4) NULL,
    [ResellerSalesUnitProductStandardCost]     DECIMAL (18, 4) NOT NULL,
    [ResellerSalesTotalProductCost]            DECIMAL (18, 4) NULL,
    [ResellerSalesAmount]                      DECIMAL (18, 4) NULL,
    [ResellerSalesTaxAmount]                   DECIMAL (18, 4) NULL,
    [ResellerSalesFreightAmount]               DECIMAL (18, 4) NULL,
    [CarrierTrackingNumber]                    NVARCHAR (25)   NULL,
    [PurchaseOrderNumber]                      NVARCHAR (25)   NULL,
    [OrderDate]                                DATETIME        NOT NULL,
    [DueDate]                                  DATETIME        NOT NULL,
    [ShipDate]                                 DATETIME        NULL
);

